server:
  port: 8081

spring:
  application:
    name: fetcher

  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    # url: jdbc:mariadb://localhost:8889/crawler_app
    url: jdbc:mariadb://mariadb:3306/crawler_app
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  pa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: redis
      port: 6379
      password: ""
      timeout: 5000ms
